"""
Unit tests for main.py

This module contains unit tests for the Meal class and functions in main.py,
including unit tests for individual functions and integration tests.
"""

import unittest
from unittest.mock import patch, MagicMock
from main import Meal, add_calories, add_meal, delete_meal

"""
All tests were generated by Claude Sonnet 4.5. The prompt used to generate these tests is as follows:

Generate unit tests for the function(s) implemented in main.py (two unit tests per function, 
and one integration test incorporating multiple functions working together)
"""

class TestMeal(unittest.TestCase):
    """Unit tests for the Meal class"""
    
    def test_meal_initialization(self):
        """Test that a Meal object is initialized correctly"""
        meal = Meal("Pasta", 500, ["noodles", "tomato sauce", "cheese"])
        
        self.assertEqual(meal.name, "Pasta")
        self.assertEqual(meal.calories, 500)
        self.assertEqual(meal.ingredients, ["noodles", "tomato sauce", "cheese"])
    
    def test_meal_initialization_empty_ingredients(self):
        """Test Meal initialization with empty ingredients list"""
        meal = Meal("Water", 0, [])
        
        self.assertEqual(meal.name, "Water")
        self.assertEqual(meal.calories, 0)
        self.assertEqual(meal.ingredients, [])


class TestAddMeal(unittest.TestCase):
    """Unit tests for the add_meal function"""
    
    @patch('builtins.input', side_effect=["Pizza", "800", "dough, cheese, tomato"])
    def test_add_meal_basic(self, mock_input):
        """Test adding a meal with valid input"""
        meals = []
        add_meal(meals)
        
        self.assertEqual(len(meals), 1)
        self.assertEqual(meals[0].name, "Pizza")
        self.assertEqual(meals[0].calories, 800)
        self.assertEqual(meals[0].ingredients, ["dough", "cheese", "tomato"])
    
    @patch('builtins.input', side_effect=["Salad", "150", "lettuce,  tomato,  cucumber"])
    def test_add_meal_strips_whitespace(self, mock_input):
        """Test that ingredient whitespace is properly stripped"""
        meals = []
        add_meal(meals)
        
        self.assertEqual(len(meals), 1)
        self.assertEqual(meals[0].ingredients, ["lettuce", "tomato", "cucumber"])


class TestDeleteMeal(unittest.TestCase):
    """Unit tests for the delete_meal function"""
    
    @patch('builtins.input', return_value="Pizza")
    @patch('builtins.print')
    def test_delete_meal_exists(self, mock_print, mock_input):
        """Test deleting a meal that exists in the list"""
        meal1 = Meal("Pizza", 800, ["dough", "cheese"])
        meal2 = Meal("Salad", 150, ["lettuce"])
        meals = [meal1, meal2]
        
        delete_meal(meals)
        
        self.assertEqual(len(meals), 1)
        self.assertEqual(meals[0].name, "Salad")
        mock_print.assert_called_once_with("Pizza has been deleted.")
    
    @patch('builtins.input', return_value="Burger")
    @patch('builtins.print')
    def test_delete_meal_not_found(self, mock_print, mock_input):
        """Test deleting a meal that doesn't exist"""
        meal1 = Meal("Pizza", 800, ["dough", "cheese"])
        meals = [meal1]
        
        delete_meal(meals)
        
        self.assertEqual(len(meals), 1)
        mock_print.assert_called_once_with("Burger not found.")

class TestIntegration(unittest.TestCase):
    """Integration tests combining multiple functions"""
    
    @patch('builtins.input', side_effect=[
        "Breakfast", "400", "eggs, toast",
        "Lunch", "600", "sandwich, chips",
        "Dinner", "800", "steak, potatoes",
        "Lunch"
    ])
    @patch('builtins.print')
    def test_add_multiple_and_delete_one(self, mock_print, mock_input):
        """Integration test: Add multiple meals and delete one"""
        meals = []
        
        # Add three meals
        add_meal(meals)
        add_meal(meals)
        add_meal(meals)
        
        self.assertEqual(len(meals), 3)
        
        # Delete the middle one
        delete_meal(meals)
        
        self.assertEqual(len(meals), 2)
        self.assertEqual(meals[0].name, "Breakfast")
        self.assertEqual(meals[1].name, "Dinner")
        mock_print.assert_called_once_with("Lunch has been deleted.")


@patch('builtins.print')
def test_add_calories_single_meal(mock_print):
    """Test calorie total for one meal"""
    meals = [Meal("Pizza", 800, ["cheese"])]
    add_calories(meals)
    mock_print.assert_called_once_with("Total calories for the day: 800")


@patch('builtins.print')
def test_add_calories_multiple_meals(mock_print):
    """Test calorie total for multiple meals"""
    meals = [
        Meal("Pizza", 800, ["cheese"]),
        Meal("Salad", 200, ["lettuce"])
    ]
    add_calories(meals)
    mock_print.assert_called_once_with("Total calories for the day: 1000")


if __name__ == '__main__':
    unittest.main()


